# Generated by Django 3.1.1 on 2020-09-26 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('videoName', models.CharField(blank=True, max_length=50, null=True)),
                ('videoPic', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0, null=True)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('Music', 'Music'), ('Movies', 'Movies'), ('Gaming', 'Gaming'), ('Education', 'Education'), ('Fashion', 'Fashion')], default=1, max_length=37)),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('subscribers', models.IntegerField(blank=True, default=0, null=True)),
                ('profilePic', models.FileField(blank=True, default='', null=True, upload_to='media')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
