# Generated by Django 3.1.1 on 2020-09-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='ProfilePic'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='videoPic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
