# Generated by Django 3.1.1 on 2020-09-28 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200927_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='likes',
        ),
        migrations.AddField(
            model_name='uservideo',
            name='likes',
            field=models.ManyToManyField(related_name='video_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
