# Generated by Django 3.1.1 on 2020-09-28 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200928_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='uservideo',
            name='dislikes',
            field=models.ManyToManyField(related_name='video_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
