# Generated by Django 3.1.1 on 2020-09-29 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200928_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='watchLater',
            field=models.ManyToManyField(related_name='watch_later', to=settings.AUTH_USER_MODEL),
        ),
    ]
