# Generated by Django 3.1.1 on 2020-09-29 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_uservideo_watchlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='totalViews',
            field=models.ManyToManyField(default=0, related_name='total_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
