# Generated by Django 3.1.1 on 2020-09-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_uservideo_totalviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='totalViews',
        ),
    ]
