# Generated by Django 3.1.1 on 2020-09-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='videos',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.uservideo'),
        ),
    ]
