# Generated by Django 3.1.1 on 2020-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200929_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplaylist',
            name='videos',
        ),
        migrations.AddField(
            model_name='userplaylist',
            name='videos',
            field=models.ManyToManyField(default=1, related_name='user_playlist', to='users.UserVideo'),
        ),
    ]
