# Generated by Django 3.1.1 on 2020-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200929_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='videos',
            field=models.ManyToManyField(related_name='user_playlist', to='users.UserVideo'),
        ),
    ]
