# Generated by Django 3.1.1 on 2020-10-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200929_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylist',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
