# Generated by Django 3.1.1 on 2020-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userprofile_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='history',
            field=models.ManyToManyField(related_name='user_history', to='users.UserVideo'),
        ),
    ]
